# Generated by Django 5.2 on 2025-04-06 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlepanier',
            options={},
        ),
        migrations.AlterModelOptions(
            name='commande',
            options={},
        ),
        migrations.AlterModelOptions(
            name='detailcommande',
            options={},
        ),
        migrations.AlterModelOptions(
            name='panier',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='articlepanier',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='panier',
            name='date_modification',
        ),
        migrations.AddField(
            model_name='panier',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='adresse',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='commande',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commande',
            name='nom_complet',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En Attente'), ('confirmee', 'Confirmée'), ('en_traitement', 'En Traitement'), ('expediee', 'Expédiée'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='detailcommande',
            name='quantite',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='panier',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
