# Generated by Django 5.2 on 2025-04-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='image_principale',
            field=models.ImageField(blank=True, null=True, upload_to='produits'),
        ),
    ]
